name: smlib3
channels:
  - defaults
  - conda-forge
  - paulscherrerinstitute
dependencies:
  - python=3.6
  - pcaspy
  - pytest
  - pytest-cov
  - pyepics
  - sphinx
  - sphinx_rtd_theme
  - twine
  - nox